language: c

env:
  global:
    # coverity token
    - secure: "THWKfpOxFbQxX8Oyg8qkNaPACdOqx4KljQYytfoSzEpGuWgDLzP5YUTq0jiZLm5BRCY3Vj+GbmYGUectpEJQ7UyccfxUipmuAMEpW1zcwzl5Pdspyz2O1rJVh5pb/qRss7VSmyieh8OJYyl5W//HGxsDU29rDPRP4oW6k2k3Zvs="

script: if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then ./travis-ci-build.sh ; fi

notifications:
  irc:
    channels:
      - "irc.freenode.org#spearmint"
    on_success: change
    on_failure: always

sudo: false

addons:
  coverity_scan:
    project:
      name: "zturtleman/mint-arena"
      description: "Build submitted via Travis CI"
    notification_email: zturtleman@gmail.com
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: coverity_scan
